name: ⏹️ Shutdown Railway (night)

on:
  schedule:
    - cron: '0 21 * * *'  # 00:00 Kyiv time (UTC+3)
  workflow_dispatch:       # Можеш вручну запустити з GitHub

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Встановити Railway CLI
        run: npm install -g railway

      - name: ⏹️ Зупинити деплой
        run: railway down --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
