name: ⏹️ Shutdown Railway

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # щодня о 00:00 за Києвом (21:00 UTC)

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Завантажити Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: ⏹️ Виконати railway down
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway down --yes
