name: Shutdown Railway

on:
  workflow_dispatch: # запуск вручну
  schedule:
    - cron: "0 21 * * *" # щодня о 00:00 за Києвом (21:00 UTC)

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout repo
        uses: actions/checkout@v3

      - name: 📦 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧪 Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: 🔑 Set Railway Token
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      - name: 🛑 Run shutdown script
        run: node scripts/shutdown.js
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
