name: ⏹️ Shutdown Railway (night)

on:
  workflow_dispatch:  # для ручного запуску
  schedule:
    - cron: '0 21 * * *'  # щодня о 00:00 за Києвом (21:00 UTC)

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Завантажити Railway CLI binary
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: 🔐 Авторизація в Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: ⏹️ Зупинка останнього деплою
        run: railway down --yes
